
language: swift
osx_image: xcode11

before_install:
  - bundle install
  - bundle exec pod install

xcode_workspace: TvOSMoreButton.xcworkspace
xcode_scheme: TvOSMoreButton
xcode_destination: platform=tvOS Simulator,OS=13.0,name=Apple TV
